import { ClerkProvider } from '@clerk/nextjs';
import { Geist, Geist_Mono } from "next/font/google";
import Footer from "./component/Footer";
import { Header } from './component/Header';
import { Header1 } from './component/Header';
import { Header2 } from './component/Header';
import './globals.css';

// Fonts setup
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          {/* Your layout components */}
          <Header />
          <Header2 />
          {children}
          <Footer />
        </body>
      </html>
    </ClerkProvider>
  );
}
